### ISSUE TITLE
F#

### ISSUE THREAD

**Issue by cherryis** [Shelly-Simpson/ABC_scrum#4]

**Comment by cherryis** [comment]
WE need fixed F.

**Comment by cherryis** [comment]
WE need fixed F.WE need fixed F.

**Comment by Shelly-Simpson** [comment]
I can see your comment :)

**Comment by cherryis** [comment]
![Image](https://user-images.githubusercontent.com/59629395/231290125-90054a71-3617-4ccf-81ab-5e187646a61a.png)
